monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.pci-0000_00_1f\\.3-platform-sof-essx8336.*"
      }
      {
        node.name = "~alsa_input.pci-0000_00_1f\\.3-platform-sof-essx8336.*"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
