font_family                 SFMono Nerd Font Mono
background_opacity          0.65
cursor_trail                1
cursor_trail_decay          0.05 0.1
cursor_trail_start_threshold 1
window_padding_width        4 10 10 10
confirm_os_window_close     0


# BEGIN_KITTY_THEME
# Gotham (Gruvbox Dark colors)
include current-theme.conf
# END_KITTY_THEME