#!/usr/bin/env bash
# Applies a theme from themes.json to everything here that can be recoloured:
# Hyprland borders, Kitty, Alacritty, Starship, btop, micro, the GTK accent,
# Satty's annotation palette, and — for the programs that ship their own
# named ports rather than taking raw hex — Obsidian, VSCodium and vim.
#
# Usage: apply-theme.sh <theme-id>
set -euo pipefail

themes_file="$HOME/.config/hypr/themes/themes.json"
theme_id="${1:-}"

if [ -z "$theme_id" ]; then
    echo "Usage: apply-theme.sh <theme-id>" >&2
    exit 1
fi

theme=$(jq -c --arg id "$theme_id" '.[] | select(.id == $id)' "$themes_file")

if [ -z "$theme" ]; then
    echo "Unknown theme: $theme_id" >&2
    exit 1
fi

get() { echo "$theme" | jq -r "$1"; }

accent=$(get '.accent')
# Window borders can differ from the accent — srcery leans on its orange
# everywhere else, so the borders take its magenta instead. Themes that say
# nothing here just use the accent, as before.
border=$(get '.border // .accent')
background=$(get '.background')
dark_background=$(get '.darkBackground')
foreground=$(get '.foreground')
muted=$(get '.muted')
red=$(get '.colors.red')
yellow=$(get '.colors.yellow')
green=$(get '.colors.green')
cyan=$(get '.colors.cyan')
blue=$(get '.colors.blue')
magenta=$(get '.colors.magenta')

# Programs that carry a real port of the scheme are switched by name instead
# of being recoloured field by field; a theme that names none of them just
# leaves those programs alone.
obsidian_snippet=$(get '.apps.obsidian // ""')
vscode_theme=$(get '.apps.vscode // ""')
vim_theme=$(get '.apps.vim // ""')

# Bright variants are optional: a theme that does not spell them out (most
# do not — only Srcery has a genuinely different second row) reuses its
# normal colours, which is what this did for every theme before.
bright_red=$(get '.bright.red // .colors.red')
bright_yellow=$(get '.bright.yellow // .colors.yellow')
bright_green=$(get '.bright.green // .colors.green')
bright_cyan=$(get '.bright.cyan // .colors.cyan')
bright_blue=$(get '.bright.blue // .colors.blue')
bright_magenta=$(get '.bright.magenta // .colors.magenta')

# Hyprland: rgba() takes hex without the leading '#' plus an alpha pair.
to_rgba() { printf 'rgba(%sff)' "${1#\#}"; }

# Mixes two hex colours: blend <from> <to> <percent-of-to>. Used for the
# raised surfaces a flat palette does not name — a block painted in the
# background colour itself is invisible against the terminal.
blend() {
    local from="${1#\#}" to="${2#\#}" pct="$3" i result a b
    result="#"

    for i in 0 2 4; do
        a=$((16#${from:$i:2}))
        b=$((16#${to:$i:2}))
        result="$result$(printf '%02x' $(( (a * (100 - pct) + b * pct) / 100 )))"
    done

    printf '%s' "$result"
}

# One and two steps above the background, for panels and inset blocks.
# A theme can name them itself (Slime does, so it only ever uses colours from
# its source image); otherwise they are blended.
surface1=$(get '.surface1 // empty')
surface2=$(get '.surface2 // empty')
[ -n "$surface1" ] || surface1=$(blend "$background" "$foreground" 9)
[ -n "$surface2" ] || surface2=$(blend "$background" "$foreground" 20)

# On a fresh machine some of these directories only exist once the program
# has run for the first time.
mkdir -p "$HOME/.config/hypr/config" "$HOME/.config/hypr/themes" \
         "$HOME/.config/kitty" "$HOME/.config/alacritty/themes"

cat > "$HOME/.config/hypr/config/colors.lua" <<EOF
-- Generated by apply-theme.sh for theme: $theme_id. Do not hand-edit — use
-- the Theme panel (Super+I) or apply-theme.sh instead, your changes will be
-- overwritten on the next theme switch.

CACHYLGREEN = "$(to_rgba "$border")"
CACHYMGREEN = "$(to_rgba "$green")"
CACHYDGREEN = "$(to_rgba "$dark_background")"
CACHYLBLUE  = "$(to_rgba "$blue")"
CACHYMBLUE  = "$(to_rgba "$muted")"
CACHYDBLUE  = "$(to_rgba "$dark_background")"
CACHYWHITE  = "$(to_rgba "$foreground")"
CACHYGREY   = "$(to_rgba "$foreground")"
CACHYGRAY   = "$(to_rgba "$muted")"
EOF

cat > "$HOME/.config/kitty/current-theme.conf" <<EOF
## Generated by apply-theme.sh for theme: $theme_id.

background $background
foreground $foreground
selection_background $muted
selection_foreground $foreground

color0  $dark_background
color1  $red
color2  $green
color3  $yellow
color4  $blue
color5  $magenta
color6  $cyan
color7  $foreground
color8  $muted
color9  $bright_red
color10 $bright_green
color11 $bright_yellow
color12 $bright_blue
color13 $bright_magenta
color14 $bright_cyan
color15 $foreground

cursor $accent
cursor_text_color $background
url_color $accent
active_border_color $accent
inactive_border_color $muted
active_tab_background $accent
active_tab_foreground $background
inactive_tab_background $dark_background
inactive_tab_foreground $muted
EOF

cat > "$HOME/.config/alacritty/themes/current.toml" <<EOF
[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "$background"
foreground = "$foreground"

[colors.normal]
black = "$dark_background"
red = "$red"
green = "$green"
yellow = "$yellow"
blue = "$blue"
magenta = "$magenta"
cyan = "$cyan"
white = "$foreground"

[colors.bright]
black = "$muted"
red = "$bright_red"
green = "$bright_green"
yellow = "$bright_yellow"
blue = "$bright_blue"
magenta = "$bright_magenta"
cyan = "$bright_cyan"
white = "$foreground"

[colors.cursor]
cursor = "$accent"
text = "$background"
EOF

# btop reads themes out of its own directory; writing one file and pointing
# the config at it beats rewriting every colour in btop.conf.
mkdir -p "$HOME/.config/btop/themes"
cat > "$HOME/.config/btop/themes/current.theme" <<EOF
# Generated by apply-theme.sh for theme: $theme_id.

theme[main_bg]="$background"
theme[main_fg]="$foreground"
theme[title]="$foreground"
theme[hi_fg]="$accent"
theme[selected_bg]="$surface1"
theme[selected_fg]="$accent"
theme[inactive_fg]="$muted"
theme[graph_text]="$foreground"
theme[meter_bg]="$surface1"
theme[proc_misc]="$accent"
theme[cpu_box]="$muted"
theme[mem_box]="$muted"
theme[net_box]="$muted"
theme[proc_box]="$muted"
theme[div_line]="$muted"

theme[temp_start]="$green"
theme[temp_mid]="$yellow"
theme[temp_end]="$red"
theme[cpu_start]="$green"
theme[cpu_mid]="$yellow"
theme[cpu_end]="$red"
theme[free_start]="$blue"
theme[free_mid]="$cyan"
theme[free_end]="$green"
theme[cached_start]="$cyan"
theme[cached_mid]="$blue"
theme[cached_end]="$magenta"
theme[available_start]="$yellow"
theme[available_mid]="$accent"
theme[available_end]="$red"
theme[used_start]="$green"
theme[used_mid]="$yellow"
theme[used_end]="$red"
theme[download_start]="$cyan"
theme[download_mid]="$blue"
theme[download_end]="$magenta"
theme[upload_start]="$yellow"
theme[upload_mid]="$accent"
theme[upload_end]="$red"
theme[process_start]="$green"
theme[process_mid]="$yellow"
theme[process_end]="$red"
EOF

if [ -f "$HOME/.config/btop/btop.conf" ]; then
    sed -i 's/^color_theme = .*/color_theme = "current"/' "$HOME/.config/btop/btop.conf"
fi

# micro: same trick — a generated colorscheme selected from settings.json.
mkdir -p "$HOME/.config/micro/colorschemes"
cat > "$HOME/.config/micro/colorschemes/current.micro" <<EOF
# Generated by apply-theme.sh for theme: $theme_id.

color-link default "$foreground,$background"
color-link comment "$muted"

color-link identifier "$blue"
color-link identifier.class "$cyan"
color-link identifier.var "$blue"

color-link constant "$magenta"
color-link constant.number "$magenta"
color-link constant.string "$green"

color-link symbol "$cyan"
color-link symbol.brackets "$foreground"
color-link symbol.tag "$blue"

color-link type "$yellow"
color-link type.keyword "$accent"
color-link type.extended "default"

color-link special "$accent"
color-link statement "$accent"
color-link preproc "$magenta"

color-link underlined "$blue"
color-link error "bold $red"
color-link todo "bold $yellow"

color-link diff-added "$green"
color-link diff-modified "$yellow"
color-link diff-deleted "$red"

color-link gutter-error "$red"
color-link gutter-warning "$yellow"

color-link statusline "$foreground,$surface1"
color-link tabbar "$foreground,$surface1"
color-link indent-char "$muted"
color-link line-number "$muted"
color-link current-line-number "$accent"

color-link cursor-line "$surface1"
color-link color-column "$surface1"
EOF

settings="$HOME/.config/micro/settings.json"

if [ -f "$settings" ]; then
    tmp=$(mktemp)
    jq '.colorscheme = "current"' "$settings" > "$tmp" && mv "$tmp" "$settings"
fi

# GTK: only the accent is worth driving — the rest of the widget colours come
# from the installed GTK theme, and fighting it produces unreadable apps.
# libadwaita reads accent_color/accent_bg_color, GTK3 the theme_selected_*.
for gtk_version in 3.0 4.0; do
    gtk_dir="$HOME/.config/gtk-$gtk_version"
    mkdir -p "$gtk_dir"
    cat > "$gtk_dir/gtk.css" <<EOF
/* Generated by apply-theme.sh for theme: $theme_id. */

@define-color accent_color $accent;
@define-color accent_bg_color $accent;
@define-color accent_fg_color $background;
@define-color theme_selected_bg_color $accent;
@define-color theme_selected_fg_color $background;
EOF
done

# Starship: only the palette block is rewritten, so the prompt's format,
# symbols and module settings survive untouched. Starship re-reads its config
# for every prompt, so open shells pick this up on their next command.
#
# The segments run light to dark from the left: accent (os/user), yellow
# (directory), cyan (git), blue (languages), then two raised surfaces for
# docker/conda and the clock. Those last two are blends rather than the
# background itself: painted in the background colour the blocks would be
# invisible against the terminal. fg1 is the dark text on the bright
# segments, fg0 the light text on the dark ones.
starship_config="$HOME/.config/starship.toml"

if [ -f "$starship_config" ]; then
    python3 - "$starship_config" "$foreground" "$dark_background" "$surface1" "$surface2" \
        "$blue" "$cyan" "$green" "$accent" "$magenta" "$red" "$yellow" <<'PYEOF'
import re
import sys

path, fg0, fg1, bg1, bg3, blue, aqua, green, orange, purple, red, yellow = sys.argv[1:]

palette = "\n".join([
    "[palettes.theme]",
    "color_fg0 = '%s'" % fg0,
    "color_fg1 = '%s'" % fg1,
    "color_bg1 = '%s'" % bg1,
    "color_bg3 = '%s'" % bg3,
    "color_blue = '%s'" % blue,
    "color_aqua = '%s'" % aqua,
    "color_green = '%s'" % green,
    "color_orange = '%s'" % orange,
    "color_purple = '%s'" % purple,
    "color_red = '%s'" % red,
    "color_yellow = '%s'" % yellow,
])

with open(path, encoding="utf-8") as handle:
    text = handle.read()

# Point the prompt at our palette, whatever it was called before, and replace
# that block's body (up to the next section header) with the theme's colours.
text = re.sub(r"(?m)^palette = .*$", "palette = 'theme'", text, count=1)
text, replaced = re.subn(
    r"(?ms)^\[palettes\.[^\]]+\]\n(?:[^\[]*?)(?=^\[|\Z)",
    palette + "\n\n",
    text,
    count=1,
)

if not replaced:
    text = text.rstrip("\n") + "\n\n" + palette + "\n"

with open(path, "w", encoding="utf-8") as handle:
    handle.write(text)
PYEOF
fi

# Obsidian is themed with CSS snippets rather than by switching themes, so
# this only swaps which colour-scheme snippet is enabled and never touches
# the vault's chosen theme. Vaults come from Obsidian's own registry, so
# every vault follows along; a vendored snippet is copied in when missing.
obsidian_registry="$HOME/.config/obsidian/obsidian.json"

if [ -n "$obsidian_snippet" ] && [ -f "$obsidian_registry" ]; then
    jq -r '.vaults | to_entries[] | .value.path' "$obsidian_registry" 2>/dev/null | while read -r vault; do
        appearance="$vault/.obsidian/appearance.json"
        [ -f "$appearance" ] || continue

        asset="$HOME/.config/hypr/themes/assets/obsidian/snippets/$obsidian_snippet.css"
        snippets_dir="$vault/.obsidian/snippets"

        # Snippets these dotfiles ship (srcery, slime) are kept in sync with
        # the copy in themes/assets, so edits to a theme reach the vault.
        # Hand-written ones (l.css) have no asset and are never touched.
        if [ -f "$asset" ] && ! cmp -s "$asset" "$snippets_dir/$obsidian_snippet.css"; then
            mkdir -p "$snippets_dir"
            cp "$asset" "$snippets_dir/$obsidian_snippet.css"
        fi

        [ -f "$snippets_dir/$obsidian_snippet.css" ] || continue

        tmp=$(mktemp)

        # Which snippets are colour schemes is decided by the themes file, so
        # utility snippets (bullets, tabs, …) are never disabled.
        if jq --arg snippet "$obsidian_snippet" \
              --argjson managed "$(jq -c '[.[].apps.obsidian // empty] | map(select(. != ""))' "$themes_file")" '
              .enabledCssSnippets = (
                  ((.enabledCssSnippets // []) - $managed) + [$snippet]
              )
          ' "$appearance" > "$tmp" 2>/dev/null; then
            mv "$tmp" "$appearance"
        else
            rm -f "$tmp"
        fi
    done
fi

# VSCodium: the theme name only works once its extension is installed, so
# say so rather than silently leaving the editor on the old colours.
vscode_settings="$HOME/.config/VSCodium/User/settings.json"

if [ -n "$vscode_theme" ] && [ -f "$vscode_settings" ]; then
    tmp=$(mktemp)

    if jq --arg theme "$vscode_theme" '.["workbench.colorTheme"] = $theme' "$vscode_settings" > "$tmp" 2>/dev/null; then
        mv "$tmp" "$vscode_settings"
    else
        rm -f "$tmp"
    fi
fi

# vim and Neovim: a generated file holding just the colorscheme line, sourced
# from the user's config, so nothing else in it is touched. The srcery
# colorscheme is vendored in the dotfiles (it is the same file for both
# editors); the monochrome fallback is one each editor ships with.
if [ -n "$vim_theme" ]; then
    vendored="$HOME/.vim/colors/$vim_theme.vim"

    write_editor_theme() {
        cat > "$1" <<EOF
" Generated by apply-theme.sh for theme: $theme_id. Do not hand-edit — it is
" rewritten on every theme switch.

if has('termguicolors')
  set termguicolors
endif

set background=dark
silent! colorscheme $vim_theme
EOF
    }

    # Appends the source line to an existing config, or writes a new one.
    hook_editor_config() {
        local config="$1" line="$2"

        if [ ! -f "$config" ]; then
            mkdir -p "$(dirname "$config")"
            printf '%s\n%s\n' "$3" "$line" > "$config"
        elif ! grep -qF "theme.vim" "$config"; then
            printf '\n%s\n%s\n' "$3" "$line" >> "$config"
        fi
    }

    mkdir -p "$HOME/.vim/colors"
    write_editor_theme "$HOME/.vim/theme.vim"
    hook_editor_config "$HOME/.vimrc" \
        "if filereadable(expand('~/.vim/theme.vim')) | source ~/.vim/theme.vim | endif" \
        '" Colours follow the desktop theme (Super+I); apply-theme.sh writes that file.'

    if command -v nvim >/dev/null 2>&1; then
        nvim_dir="${XDG_CONFIG_HOME:-$HOME/.config}/nvim"
        mkdir -p "$nvim_dir/colors"
        write_editor_theme "$nvim_dir/theme.vim"

        # Neovim can carry the colorscheme in its own colors/ directory; the
        # vendored file is copied rather than symlinked so it survives the
        # dotfiles being moved.
        [ -f "$vendored" ] && cp "$vendored" "$nvim_dir/colors/$vim_theme.vim"

        # init.lua wins over init.vim when both exist, so hook whichever the
        # user already has and default to Lua.
        if [ -f "$nvim_dir/init.vim" ] && [ ! -f "$nvim_dir/init.lua" ]; then
            hook_editor_config "$nvim_dir/init.vim" \
                "if filereadable(stdpath('config') . '/theme.vim') | source theme.vim | endif" \
                '" Colours follow the desktop theme (Super+I).'
        else
            hook_editor_config "$nvim_dir/init.lua" \
                "vim.cmd('silent! source ' .. vim.fn.stdpath('config') .. '/theme.vim')" \
                '-- Colours follow the desktop theme (Super+I); apply-theme.sh writes that file.'
        fi
    fi
fi

# Satty's quick-pick annotation colours.
satty_config="$HOME/.config/satty/config.toml"

if [ -f "$satty_config" ]; then
    python3 - "$satty_config" "$red" "$green" "$yellow" "$blue" "$magenta" "$cyan" <<'PYEOF'
import re
import sys

path, *colors = sys.argv[1:]
palette = "palette = [\n" + "".join('    "%s",\n' % c for c in colors) + "]"

with open(path, encoding="utf-8") as handle:
    text = handle.read()

# Only the palette inside [color-palette]; the commented-out examples and the
# empty `custom` list below it are left alone.
updated, count = re.subn(r"palette = \[[^\]]*\]", palette, text, count=1)

if count:
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(updated)
PYEOF
fi

hyprctl reload >/dev/null 2>&1 || true

# GTK apps re-read gtk.css when the theme name changes; poking xsettingsd is
# the least invasive nudge available and is a no-op when it is not running.
pkill -HUP -x xsettingsd 2>/dev/null || true

# Kitty re-reads its config on SIGUSR1, so open terminals pick up the new
# colors immediately instead of only new windows. (Alacritty already
# live-reloads the imported theme file on its own; btop and micro pick the
# new theme up the next time they start.)
pkill -USR1 -x kitty 2>/dev/null || true

echo "$theme_id" > "$HOME/.config/hypr/themes/current"
