#!/usr/bin/env bash
# Applies a theme from themes.json to Hyprland borders, Kitty, and Alacritty.
# Usage: apply-theme.sh <theme-id>
set -euo pipefail

themes_file="$HOME/.config/hypr/themes/themes.json"
theme_id="${1:-}"

if [ -z "$theme_id" ]; then
    echo "Usage: apply-theme.sh <theme-id>" >&2
    exit 1
fi

theme=$(jq -c --arg id "$theme_id" '.[] | select(.id == $id)' "$themes_file")

if [ -z "$theme" ]; then
    echo "Unknown theme: $theme_id" >&2
    exit 1
fi

get() { echo "$theme" | jq -r "$1"; }

accent=$(get '.accent')
background=$(get '.background')
dark_background=$(get '.darkBackground')
foreground=$(get '.foreground')
muted=$(get '.muted')
red=$(get '.colors.red')
yellow=$(get '.colors.yellow')
green=$(get '.colors.green')
cyan=$(get '.colors.cyan')
blue=$(get '.colors.blue')
magenta=$(get '.colors.magenta')

# Hyprland: rgba() takes hex without the leading '#' plus an alpha pair.
to_rgba() { printf 'rgba(%sff)' "${1#\#}"; }

cat > "$HOME/.config/hypr/config/colors.lua" <<EOF
-- Generated by apply-theme.sh for theme: $theme_id. Do not hand-edit — use
-- the Theme panel (Super+I) or apply-theme.sh instead, your changes will be
-- overwritten on the next theme switch.

CACHYLGREEN = "$(to_rgba "$accent")"
CACHYMGREEN = "$(to_rgba "$green")"
CACHYDGREEN = "$(to_rgba "$dark_background")"
CACHYLBLUE  = "$(to_rgba "$blue")"
CACHYMBLUE  = "$(to_rgba "$muted")"
CACHYDBLUE  = "$(to_rgba "$dark_background")"
CACHYWHITE  = "$(to_rgba "$foreground")"
CACHYGREY   = "$(to_rgba "$foreground")"
CACHYGRAY   = "$(to_rgba "$muted")"
EOF

cat > "$HOME/.config/kitty/current-theme.conf" <<EOF
## Generated by apply-theme.sh for theme: $theme_id.

background $background
foreground $foreground
selection_background $muted
selection_foreground $foreground

color0  $dark_background
color1  $red
color2  $green
color3  $yellow
color4  $blue
color5  $magenta
color6  $cyan
color7  $foreground
color8  $muted
color9  $red
color10 $green
color11 $yellow
color12 $blue
color13 $magenta
color14 $cyan
color15 $foreground
EOF

cat > "$HOME/.config/alacritty/themes/current.toml" <<EOF
[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "$background"
foreground = "$foreground"

[colors.normal]
black = "$dark_background"
red = "$red"
green = "$green"
yellow = "$yellow"
blue = "$blue"
magenta = "$magenta"
cyan = "$cyan"
white = "$foreground"

[colors.bright]
black = "$muted"
red = "$red"
green = "$green"
yellow = "$yellow"
blue = "$blue"
magenta = "$magenta"
cyan = "$cyan"
white = "$foreground"
EOF

hyprctl reload >/dev/null 2>&1 || true

# Kitty re-reads its config on SIGUSR1, so open terminals pick up the new
# colors immediately instead of only new windows. (Alacritty already
# live-reloads the imported theme file on its own.)
pkill -USR1 -x kitty 2>/dev/null || true

echo "$theme_id" > "$HOME/.config/hypr/themes/current"
