#!/usr/bin/env bash
# Applies the Hyprland look the Glacier settings panel's Hyprland tab owns.
#
# Usage: set-compositor.sh [--glass 0|1] [--opacity 30-100] [--gaps 0-24]
#                          [--rounding 0-24] [--border 0-6] [--blur 0|1]
#                          [--animations 0|1] [--dim 0|1]
#
# Anything left out keeps its default. The shell always passes the full set,
# so the generated file below is a complete picture of the panel's state.
#
# Applied twice over: once live through `hyprctl eval` so a change is instant,
# and once into config/compositor.lua so it survives a reload (the theme
# switcher reloads Hyprland). That file is required last by hyprland.lua, so
# it wins over decorations.lua and plugins.lua.
#
# The opacity also drives the terminals, as the single control for how see-
# through everything is. They cannot take it the Hyprland way: windowrules.lua
# pins them to "1.0 override" because compositor alpha fades their text too.
# So the same value goes to kitty's own background_opacity (set-kitty.sh),
# which fades only the background.
set -euo pipefail

glass=1 opacity=65 gaps=6 rounding=18 border=0 blur=1 animations=1 dim=0

while [ $# -gt 0 ]; do
    case "$1" in
        --glass) glass="$2" ;;
        --opacity) opacity="$2" ;;
        --gaps) gaps="$2" ;;
        --rounding) rounding="$2" ;;
        --border) border="$2" ;;
        --blur) blur="$2" ;;
        --animations) animations="$2" ;;
        --dim) dim="$2" ;;
        *) echo "unknown option: $1" >&2; exit 1 ;;
    esac
    shift 2
done

check_range() {
    local name="$1" value="$2" low="$3" high="$4"

    if ! [ "$value" -ge "$low" ] 2>/dev/null || ! [ "$value" -le "$high" ] 2>/dev/null; then
        echo "$name must be $low-$high, got: $value" >&2
        exit 1
    fi
}

check_range glass "$glass" 0 1
check_range opacity "$opacity" 0 100
check_range gaps "$gaps" 0 40
check_range rounding "$rounding" 0 40
check_range border "$border" 0 10
check_range blur "$blur" 0 1
check_range animations "$animations" 0 1
check_range dim "$dim" 0 1

lua_bool() { [ "$1" -eq 1 ] && echo true || echo false; }

# Inactive windows sit a touch further back, 3 points below the active ones,
# and fully opaque stays fully opaque.
active=$(printf '%d.%02d' $((opacity / 100)) $((opacity % 100)))
inactive_pct=$((opacity >= 100 ? 100 : opacity - 3))
[ "$inactive_pct" -lt 0 ] && inactive_pct=0
inactive=$(printf '%d.%02d' $((inactive_pct / 100)) $((inactive_pct % 100)))

table="general = { gaps_in = $gaps, gaps_out = $gaps, border_size = $border },
    decoration = {
        rounding = $rounding,
        active_opacity = $active,
        inactive_opacity = $inactive,
        dim_inactive = $(lua_bool "$dim"),
        blur = { enabled = $(lua_bool "$blur") },
    },
    animations = { enabled = $(lua_bool "$animations") },
    plugin = { hyprglass = { enabled = $glass } }"

cat > "$HOME/.config/hypr/config/compositor.lua" <<EOF
-- Generated by set-compositor.sh. Do not hand-edit — use the Hyprland tab of
-- the Glacier settings panel (Super+S), your changes will be overwritten.
--
-- Required last by hyprland.lua so these win over decorations.lua and
-- plugins.lua.

hl.config({
    $table
})
EOF

# This Hyprland uses the Lua parser, where `hyprctl keyword` is refused —
# `eval` takes the same table the config files pass to hl.config.
hyprctl eval "hl.config({ $table })" >/dev/null 2>&1 || true

# Only rewrites kitty.conf (and reloads kitty) when the value actually changes,
# since this also runs on every shell start.
kitty_config="$HOME/.config/kitty/kitty.conf"
current=$(grep -m1 -E '^background_opacity' "$kitty_config" 2>/dev/null | awk '{print $2}')

if [ -x "$HOME/.config/hypr/scripts/set-kitty.sh" ] && [ "$current" != "$active" ]; then
    "$HOME/.config/hypr/scripts/set-kitty.sh" background_opacity "$active" || true
fi
