#!/usr/bin/env bash
# Sets the compositor looks the Glacier settings panel exposes: the HyprGlass
# blur plugin, how transparent windows are, and whether windows are spaced
# out or packed edge to edge.
#
# Usage: set-compositor.sh <glass 0|1> <opacity 0-100> [edge-to-edge 0|1]
#
# Transparency reaches each surface by the route that looks best on it:
#
#   * ordinary windows   Hyprland's decoration opacity
#   * terminals          the terminal's own background opacity, because
#                        compositor alpha fades the text along with the
#                        background, and windowrules.lua deliberately pins
#                        terminals to "1.0 override" for that reason
#   * browsers, players  left fully opaque, as windowrules.lua has them
#
# Edge to edge drops every gap and squares the corners, which would
# otherwise leave wallpaper showing in the notches between windows, and
# turns on a border so neighbouring windows are still told apart.
#
# The Hyprland half is applied twice over: once live through `hyprctl eval`
# so the change is instant, and once into config/compositor.lua so it
# survives a reload (the theme switcher reloads Hyprland). That file is
# required last by hyprland.lua, so it wins over decorations.lua and
# plugins.lua.
set -euo pipefail

glass="${1:-1}"
opacity="${2:-65}"
edge="${3:-0}"

case "$glass" in
    0|1) ;;
    *) echo "glass must be 0 or 1, got: $glass" >&2; exit 1 ;;
esac

case "$edge" in
    0|1) ;;
    *) echo "edge-to-edge must be 0 or 1, got: $edge" >&2; exit 1 ;;
esac

if ! [ "$opacity" -ge 0 ] 2>/dev/null || ! [ "$opacity" -le 100 ] 2>/dev/null; then
    echo "opacity must be 0-100, got: $opacity" >&2
    exit 1
fi

# Inactive windows sit a touch further back, the same 3 points apart as the
# hand-written config had, and fully opaque stays fully opaque.
active=$(printf '%d.%02d' $((opacity / 100)) $((opacity % 100)))
inactive_pct=$((opacity >= 100 ? 100 : opacity - 3))
[ "$inactive_pct" -lt 0 ] && inactive_pct=0
inactive=$(printf '%d.%02d' $((inactive_pct / 100)) $((inactive_pct % 100)))

if [ "$edge" -eq 1 ]; then
    gaps_in=0
    gaps_out=0
    border_size=2
    rounding=0
else
    gaps_in=6
    gaps_out=6
    border_size=0
    rounding=18
fi

layout="general = { gaps_in = $gaps_in, gaps_out = $gaps_out, border_size = $border_size }, decoration = { rounding = $rounding }"

cat > "$HOME/.config/hypr/config/compositor.lua" <<EOF
-- Generated by set-compositor.sh. Do not hand-edit — use the Glacier
-- settings panel (Super+S), your changes will be overwritten.
--
-- Required last by hyprland.lua so these win over decorations.lua and
-- plugins.lua.

hl.config({
    general = {
        gaps_in = $gaps_in,
        gaps_out = $gaps_out,
        border_size = $border_size,
    },
    decoration = {
        rounding = $rounding,
        active_opacity = $active,
        inactive_opacity = $inactive,
    },
    plugin = {
        hyprglass = {
            enabled = $glass,
        },
    },
})
EOF

# This Hyprland uses the Lua parser, where `hyprctl keyword` is refused —
# `eval` takes the same table the config files pass to hl.config.
hyprctl eval "hl.config({ $layout, plugin = { hyprglass = { enabled = $glass } } })" >/dev/null 2>&1 || true
hyprctl eval "hl.config({ decoration = { active_opacity = $active, inactive_opacity = $inactive } })" >/dev/null 2>&1 || true

# Kitty: only the background fades, so text stays readable at any setting.
# It re-reads its config on SIGUSR1, so open terminals follow immediately.
kitty_config="$HOME/.config/kitty/kitty.conf"

if [ -f "$kitty_config" ]; then
    if grep -q '^background_opacity' "$kitty_config"; then
        sed -i "s/^background_opacity.*/background_opacity          $active/" "$kitty_config"
    else
        printf 'background_opacity          %s\n' "$active" >> "$kitty_config"
    fi

    pkill -USR1 -x kitty 2>/dev/null || true
fi
