-- CachyOS Hyprland Configuration

require("config.animations")
require("config.autostart")
require("config.colors")
require("config.decorations")
require("config.variables")
require("config.environment")
require("config.inputs")
require("config.binds")
require("config.misc")
require("config.plugins")
require("config.monitors")
require("config.windowrules")
require("config.workspaces")

-- Last, so the settings panel's compositor overrides win over the values
-- decorations.lua and plugins.lua set above. Generated by set-compositor.sh.
pcall(require, "config.compositor")
