-- Generated by apply-theme.sh for theme: monochrome. Do not hand-edit — use
-- the Theme panel (Super+I) or apply-theme.sh instead, your changes will be
-- overwritten on the next theme switch.

CACHYLGREEN = "rgba(d6d6d6ff)"
CACHYMGREEN = "rgba(9a9a9aff)"
CACHYDGREEN = "rgba(020202ff)"
CACHYLBLUE  = "rgba(7f7f7fff)"
CACHYMBLUE  = "rgba(8d8d8dff)"
CACHYDBLUE  = "rgba(020202ff)"
CACHYWHITE  = "rgba(d4d4d4ff)"
CACHYGREY   = "rgba(d4d4d4ff)"
CACHYGRAY   = "rgba(8d8d8dff)"
