-- Generated by apply-theme.sh for theme: srcery. Do not hand-edit — use
-- the Theme panel (Super+I) or apply-theme.sh instead, your changes will be
-- overwritten on the next theme switch.

CACHYLGREEN = "rgba(ff5c8fff)"
CACHYMGREEN = "rgba(519f50ff)"
CACHYDGREEN = "rgba(121110ff)"
CACHYLBLUE  = "rgba(2c78bfff)"
CACHYMBLUE  = "rgba(918175ff)"
CACHYDBLUE  = "rgba(121110ff)"
CACHYWHITE  = "rgba(fce8c3ff)"
CACHYGREY   = "rgba(fce8c3ff)"
CACHYGRAY   = "rgba(918175ff)"
